/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto_ordinario;

import javax.swing.JOptionPane;

public class CarritoProducto extends javax.swing.JPanel {
    
    String nombres, imagen, subtotal;
        public CarritoProducto(String nombre, String subtotal, String imagen) {
            initComponents();
            this.nombres = nombre;
            this.subtotal = subtotal;
            this.imagen = imagen;

            this.nombre.setText(nombre);
            this.precio.setText(subtotal);

            java.net.URL imgURL = getClass().getResource("/proyecto_ordinario/imagenes/" + imagen);
            if (imgURL != null) {
                this.Icono.setIcon(new javax.swing.ImageIcon(imgURL));
            } else {
                System.out.println("Error de imagen: " + imagen);
            }
        }

    
    
    
    public CarritoProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Icono = new javax.swing.JLabel();
        Gresta = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        precio1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_ordinario/imagenes/b15.png"))); // NOI18N
        add(Icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 105));

        Gresta.setBackground(new java.awt.Color(114, 141, 141));
        Gresta.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Gresta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_ordinario/imagenes/cantidad_producto.png"))); // NOI18N
        Gresta.setText("Eliminar");
        Gresta.setBorderPainted(false);
        Gresta.setContentAreaFilled(false);
        Gresta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Gresta.addActionListener(this::GrestaActionPerformed);
        add(Gresta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 35, 130, 40));

        nombre.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        nombre.setText("Nombre de producto");
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 320, 30));

        precio.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        precio.setText("subtotal");
        add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 120, 30));

        precio1.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        precio1.setText("Subtotal   $");
        add(precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void GrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrestaActionPerformed
        java.awt.Container contenedor = this.getParent();
        contenedor.remove(this);
        contenedor.revalidate();
        contenedor.repaint();
        eliminarDeCarrito();
        recalcularTotales(contenedor);
    }//GEN-LAST:event_GrestaActionPerformed

    private void eliminarDeCarrito() {
        try {
            java.sql.Connection c = DBConexion.getConexion();
            java.sql.PreparedStatement ps = c.prepareStatement(
                "DELETE FROM carrito WHERE nombre_producto=? AND subtotal=? AND imagen=? LIMIT 1");
            ps.setString(1, nombres);
            ps.setDouble(2, Double.parseDouble(subtotal));
            ps.setString(3, imagen);
            ps.executeUpdate();
        } catch (java.sql.SQLException e) {
            System.out.println("Error al eliminar del carrito: " + e.getMessage());
        }
    }

    private void recalcularTotales(java.awt.Container contenedor) {
        java.awt.Container carritoFrame = contenedor.getParent();
        while (carritoFrame != null && !(carritoFrame instanceof CARRITO)) {
            carritoFrame = carritoFrame.getParent();
        }
        if (carritoFrame instanceof CARRITO) {
            ((CARRITO) carritoFrame).recalcular();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gresta;
    private javax.swing.JLabel Icono;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel precio1;
    // End of variables declaration//GEN-END:variables
}
