/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_ordinario;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Ganda
 */
public class CrearCuenta extends javax.swing.JFrame {
    private JFrame inicio;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearCuenta.class.getName());

    /**
     * Creates new form CrearCuenta
     */
    public CrearCuenta() {
        initComponents();
    }
    
    public CrearCuenta(JFrame inicio) {
        this.inicio=inicio;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contrasena_txt = new javax.swing.JTextField();
        usuario_txt = new javax.swing.JTextField();
        nombre_txt1 = new javax.swing.JTextField();
        crear_cuenta = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contrasena_txt.setBackground(new java.awt.Color(244, 244, 244));
        contrasena_txt.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        contrasena_txt.setForeground(new java.awt.Color(153, 153, 153));
        contrasena_txt.setText("Indique su contraseña");
        contrasena_txt.setToolTipText("");
        contrasena_txt.setBorder(null);
        contrasena_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contrasena_txtFocusGained(evt);
            }
        });
        contrasena_txt.addActionListener(this::contrasena_txtActionPerformed);
        getContentPane().add(contrasena_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 320, 40));

        usuario_txt.setBackground(new java.awt.Color(244, 244, 244));
        usuario_txt.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        usuario_txt.setForeground(new java.awt.Color(153, 153, 153));
        usuario_txt.setText("Ingrese nombre");
        usuario_txt.setToolTipText("");
        usuario_txt.setBorder(null);
        usuario_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usuario_txtFocusGained(evt);
            }
        });
        usuario_txt.addActionListener(this::usuario_txtActionPerformed);
        getContentPane().add(usuario_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 320, 40));

        nombre_txt1.setBackground(new java.awt.Color(244, 244, 244));
        nombre_txt1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        nombre_txt1.setForeground(new java.awt.Color(153, 153, 153));
        nombre_txt1.setText("Ingrese el usuario que desea usar");
        nombre_txt1.setToolTipText("");
        nombre_txt1.setBorder(null);
        nombre_txt1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombre_txt1FocusGained(evt);
            }
        });
        nombre_txt1.addActionListener(this::nombre_txt1ActionPerformed);
        getContentPane().add(nombre_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 320, 40));

        crear_cuenta.setBackground(new java.awt.Color(104, 45, 3));
        crear_cuenta.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        crear_cuenta.setForeground(new java.awt.Color(255, 255, 255));
        crear_cuenta.setText("Crear cuenta");
        crear_cuenta.setBorderPainted(false);
        crear_cuenta.setOpaque(true);
        crear_cuenta.addActionListener(this::crear_cuentaActionPerformed);
        getContentPane().add(crear_cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 200, 30));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_ordinario/imagenes/confirmar_crear.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 360, 50));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_ordinario/imagenes/logo_crearcuenta.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Contraseña:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 330, 20));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_ordinario/imagenes/campo_creacuenta.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 360, 58));

        jLabel7.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Nombre:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 330, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_ordinario/imagenes/campo_creacuenta.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 360, 58));

        jLabel8.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Usuario:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 330, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_ordinario/imagenes/campo_creacuenta.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 360, 58));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_ordinario/imagenes/marco_crearcuenta.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_ordinario/imagenes/fondo_cafeteria.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crear_cuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_cuentaActionPerformed
        String nombre = usuario_txt.getText().trim();
        String usuarioId = nombre_txt1.getText().trim();
        String contrasena = contrasena_txt.getText().trim();
        if (nombre.isEmpty() || usuarioId.isEmpty() || contrasena.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Complete todos los campos.");
            return;
        }
        try {
            java.sql.Connection c = DBConexion.getConexion();
            java.sql.PreparedStatement ps = c.prepareStatement(
                "INSERT INTO usuarios (nombre, usuario, contrasena) VALUES (?,?,?)");
            ps.setString(1, nombre);
            ps.setString(2, usuarioId);
            ps.setString(3, contrasena);
            ps.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Cuenta creada exitosamente.");
            inicio.setExtendedState(MAXIMIZED_BOTH);
            inicio.setEnabled(true);
            this.dispose();
        } catch (java.sql.SQLIntegrityConstraintViolationException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "El usuario '" + usuarioId + "' ya existe.");
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error de BD: " + e.getMessage());
        }
    }//GEN-LAST:event_crear_cuentaActionPerformed

    private void contrasena_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contrasena_txtFocusGained
        contrasena_txt.setForeground(Color.BLACK);
        contrasena_txt.setText("");
    }//GEN-LAST:event_contrasena_txtFocusGained

    private void contrasena_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasena_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasena_txtActionPerformed

    private void usuario_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuario_txtFocusGained
        usuario_txt.setForeground(Color.BLACK);
       usuario_txt.setText("");
    }//GEN-LAST:event_usuario_txtFocusGained

    private void usuario_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuario_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuario_txtActionPerformed

    private void nombre_txt1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombre_txt1FocusGained
        nombre_txt1.setForeground(Color.BLACK);
       nombre_txt1.setText("");
        
    }//GEN-LAST:event_nombre_txt1FocusGained

    private void nombre_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_txt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CrearCuenta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contrasena_txt;
    private javax.swing.JButton crear_cuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField nombre_txt1;
    private javax.swing.JTextField usuario_txt;
    // End of variables declaration//GEN-END:variables
}
