/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_ordinario;

import java.awt.Color;

/**
 *
 * @author Ganda
 */
public class Inicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inicio.class.getName());
    private String usuario,contrasena;
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        marco.setAlignmentX((WIDTH-marco.getWidth())/2);
        marco.setAlignmentX((HEIGHT-marco.getHeight())/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contra_textf1 = new javax.swing.JTextField();
        usuario_textf = new javax.swing.JTextField();
        crear = new javax.swing.JButton();
        linea = new javax.swing.JLabel();
        iniciar_ses = new javax.swing.JButton();
        Invitado = new javax.swing.JButton();
        iniciar_sesion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cuadro_usuario = new javax.swing.JLabel();
        cuadro_contraseña1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Bienvenid = new javax.swing.JLabel();
        marco = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contra_textf1.setBackground(new java.awt.Color(244, 244, 244));
        contra_textf1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        contra_textf1.setForeground(new java.awt.Color(153, 153, 153));
        contra_textf1.setText("Ingrese su contraseña");
        contra_textf1.setToolTipText("");
        contra_textf1.setBorder(null);
        contra_textf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contra_textf1FocusGained(evt);
            }
        });
        getContentPane().add(contra_textf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 430, 400, 40));

        usuario_textf.setBackground(new java.awt.Color(244, 244, 244));
        usuario_textf.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        usuario_textf.setForeground(new java.awt.Color(153, 153, 153));
        usuario_textf.setText("Ingrese su nombre");
        usuario_textf.setToolTipText("");
        usuario_textf.setBorder(null);
        usuario_textf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usuario_textfFocusGained(evt);
            }
        });
        usuario_textf.addActionListener(this::usuario_textfActionPerformed);
        getContentPane().add(usuario_textf, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, 400, 40));

        crear.setBackground(new java.awt.Color(239, 235, 233));
        crear.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        crear.setText("Crear cuenta");
        crear.setBorderPainted(false);
        crear.setOpaque(true);
        crear.addActionListener(this::crearActionPerformed);
        getContentPane().add(crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 660, 200, 30));

        linea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_ordinario/imagenes/Line 3.png"))); // NOI18N
        getContentPane().add(linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 560, 610, 60));

        iniciar_ses.setBackground(new java.awt.Color(104, 45, 3));
        iniciar_ses.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        iniciar_ses.setForeground(new java.awt.Color(255, 255, 255));
        iniciar_ses.setText("Iniciar sesión");
        iniciar_ses.setBorderPainted(false);
        iniciar_ses.setOpaque(true);
        iniciar_ses.addActionListener(this::iniciar_sesActionPerformed);
        getContentPane().add(iniciar_ses, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 516, 405, 30));

        Invitado.setBackground(new java.awt.Color(239, 235, 233));
        Invitado.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        Invitado.setText("Acceder como invitado");
        Invitado.setBorderPainted(false);
        Invitado.setOpaque(true);
        Invitado.addActionListener(this::InvitadoActionPerformed);
        getContentPane().add(Invitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 620, 240, 30));

        iniciar_sesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iniciar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_ordinario/imagenes/Rectangle 20.png"))); // NOI18N
        getContentPane().add(iniciar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, 610, 60));

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Contraseña:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, 330, 20));

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Usuario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 320, 330, 20));

        cuadro_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_ordinario/imagenes/Rectangle 17.png"))); // NOI18N
        getContentPane().add(cuadro_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 620, 60));

        cuadro_contraseña1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuadro_contraseña1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_ordinario/imagenes/Rectangle 17.png"))); // NOI18N
        getContentPane().add(cuadro_contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 620, 60));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("para iniciar sesión:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 330, 30));

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingresa tu contraseña y correo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 210, 350, 30));

        Bienvenid.setFont(new java.awt.Font("Perpetua Titling MT", 1, 80)); // NOI18N
        Bienvenid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bienvenid.setText("Bienvenido");
        getContentPane().add(Bienvenid, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 620, -1));

        marco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_ordinario/imagenes/marco2.png"))); // NOI18N
        getContentPane().add(marco, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 80, 1226, 650));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_ordinario/imagenes/fondo_galletas.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1940, 1090));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuario_textfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuario_textfFocusGained
        usuario_textf.setForeground(Color.BLACK);
        usuario_textf.setText("");
       
       
    }//GEN-LAST:event_usuario_textfFocusGained

    private void contra_textf1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contra_textf1FocusGained
         contra_textf1.setForeground(Color.BLACK);
         contra_textf1.setText("");
        
    }//GEN-LAST:event_contra_textf1FocusGained

    private void iniciar_sesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar_sesActionPerformed
        usuario = usuario_textf.getText().trim();
        contrasena = contra_textf1.getText();
        try {
            java.sql.Connection c = DBConexion.getConexion();
            java.sql.PreparedStatement ps = c.prepareStatement(
                "SELECT usuario FROM usuarios WHERE usuario=? AND contrasena=?");
            ps.setString(1, usuario);
            ps.setString(2, contrasena);
            java.sql.ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                Sesion.usuario = rs.getString("usuario");
                Pantalla_Principal p = new Pantalla_Principal(false);
                p.setVisible(true);
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Usuario o contraseña incorrectos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error de BD: " + e.getMessage());
        }
    }//GEN-LAST:event_iniciar_sesActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        this.setEnabled(false);
        CrearCuenta n= new CrearCuenta(this);
        n.setVisible(true);
    }//GEN-LAST:event_crearActionPerformed

    private void InvitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvitadoActionPerformed
        Sesion.usuario = "invitado";
        Pantalla_Principal p = new Pantalla_Principal(true);
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InvitadoActionPerformed

    private void usuario_textfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuario_textfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuario_textfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Inicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenid;
    private javax.swing.JButton Invitado;
    private javax.swing.JTextField contra_textf1;
    private javax.swing.JButton crear;
    private javax.swing.JLabel cuadro_contraseña1;
    private javax.swing.JLabel cuadro_usuario;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton iniciar_ses;
    private javax.swing.JLabel iniciar_sesion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel linea;
    private javax.swing.JLabel marco;
    private javax.swing.JTextField usuario_textf;
    // End of variables declaration//GEN-END:variables
}
